title: Biogame
baseurl: ""            # blank for local development
url: ""                # empty for local builds
permalink: pretty      # enables trailing slashes (e.g., /hub/)

markdown: kramdown

exclude:
  - Makefile
  - node_modules
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
