title: Biogame
baseurl: "/frontend2" 
url: ""                # leave empty for local builds
permalink: pretty      # enables trailing slashes (e.g., /hub/ instead of /hub.html)

markdown: kramdown

exclude:
  - Makefile
  - node_modules
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
