# _config.yml
title: Biogame
baseurl: "" # blank for local development
url: ""    # empty for local builds
permalink: pretty # enables trailing slashes (e.g., /hub/)

markdown: Kramdown

exclude:
  - Makefile
  - node_modules
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock

# ADD THIS SECTION BELOW THE EXCLUDE LIST
include:
  - assets # This line tells Jekyll to explicitly include the assets folder

defaults:
  - scope:
      path: ""
    type: "pages"
    values:
      layout: default